### PR TITLE
Rippling MDM

### PR DESCRIPTION
**Pull request by kjudie**
Rippling MDM Features add to the MDM comparison table

### CODE REVIEW

**Comment by hkystar35** [comment]
@kjudie 
First, thank you!

Second, 2 issues:

- You missed adding the extra column to the Markdown formatted table on line 29:
```md
|---|---|---|---|---|---|---|---|---|---|---|---|
```
should be
```md
|---|---|---|---|---|---|---|---|---|---|---|---|---|
```
- Please remove the `.DS_STORE` file from your PR
  - You can create a `.gitignore` in the root of your cloned repo and add this to it:
```
**/.[Dd][Ss]_[Ss][Tt][Oo][Rr][Ee]
```
(the [Ds] is how you can make a case-insensitive line to ensure `.DS_Store` and `.DS_STORE` are excluded.)

**Review by hkystar35 — CHANGES_REQUESTED** [review]
Marking as changes needed. See previous comment.

**Review by kjudie — COMMENTED** [review]
Update to gitignore rules

**Comment by hkystar35** [comment]
Closing PR. Changes for Rippling MDM added by me  on https://github.com/hkystar35/MDM/commit/bf8f4dc684ddd1879ff726cba114d2a264296855 and typo fix on https://github.com/hkystar35/MDM/commit/06769305615dd333770e870f8ebb172bd7ce5054

**Pull request closed without merging**
